spring:
  application:
    name: spring-security-study

  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  ############# local mode #############
  #  h2:
  #    console:
  #      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
  #      path: /h2-console  # H2 Console? Path
  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  #  datasource:
  #    driver-class-name: org.h2.Driver  # Database? H2? ?????.
  #    url: jdbc:h2:~/testDB  # H2 ?? ??
  #    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
  #    password:  # H2 ?? ? ??? password ?? (??? ??? ??)
  ############# ?? mode #############
  #  datasource:
  #    driver-class-name: org.h2.Driver  # Database? H2? ?????.
  #    url: jdbc:h2:tcp://localhost/~/test # H2 ?? ??
  #    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
  #    password:  # H2 ?? ? ??? password ?? (??? ??? ??)
  ############# p6spy ?? mode #############
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:tcp://localhost/~/settlement # H2 ?? ??
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password:  # H2 ?? ? ??? password ?? (??? ??? ??)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        default_batch_fetch_size: 30
#        jdbc:
#          batch_size: 100
# ?? ?? ??
logging:
  level:
    p6spy: debug
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
  charset:
    console: UTF-8
#  file:
#    path: /logs
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace # ?? ???? ????? ???? ??

#p6spy query logging
decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j
  tracing.include-parameter-values: true