name: spring-security-study

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정
    steps:
      - name: Display Secret
        run: echo "Your secret key is ${{ secrets.KJC_TEST_DB_PASSWORD }}"

      - name: Save secret to a file
        run: echo "${{ secrets.KJC_TEST_DB_PASSWORD }}" > secret-key.txt

      - name: Upload secret file
        uses: actions/upload-artifact@v4
        with:
          name: secret-key
          path: secret-key.txt