name: spring-security-study

on:
  push:
    branches:
      - master

jobs:
  build:
    steps: Set up environment
    run: |
      echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      echo "API_KEY=${{ secrets.API_KEY }}" >> .env
