name: spring-security-study

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정
    steps:
      - name: Display Secret
        run: echo "Your secret key is ${{ secrets.KJC_TEST_DB_PASSWORD }}"
